Add the ability to add volumes to master/worker pods
hansehe/locust pull request #1
Opened 2020-12-24 14:48 UTC by NirNaturalInt

2020-12-24 14:54 UTC, Moshem123 requested changes

2020-12-24 14:54 UTC, Moshem123 commented on helm/locust/templates/deployment-master.yaml
> +          {{- end }}
```suggestion
          {{- if .Values.master.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.master.volumeMounts | nindent 12 }}
          {{- end }}
```

2020-12-24 14:54 UTC, Moshem123 commented on helm/locust/templates/deployment-master.yaml
> +      {{- end }}
```suggestion
      {{- if .Values.master.volumes }}
      volumes:
        {{ toYaml .Values.master.volumes | nindent 8 }}
      {{- end }}
```

2020-12-24 14:54 UTC, Moshem123 commented on helm/locust/templates/deployment-worker.yaml
> +          {{- end }}
```suggestion
          {{- if .Values.worker.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.worker.volumeMounts | nindent 12 }}
          {{- end }}
```

2020-12-24 14:54 UTC, Moshem123 commented on helm/locust/templates/deployment-worker.yaml
> +      {{- end }}
```suggestion
      {{- if .Values.worker.volumes }}
      volumes:
        {{ toYaml .Values.worker.volumes | nindent 8 }}
      {{- end }}
```

2020-12-24 14:54 UTC, Moshem123 commented on helm/locust/values.yaml
> +  ## Additional volumes to the master pod.
```suggestion
  volumeMounts: []
  ## volumeMounts for the master container
  #  - name: locust-file
  #   mountPath: /locust
  volumes: []
  ## volumes for the master pod.
```

2020-12-24 14:54 UTC, Moshem123 commented on helm/locust/values.yaml
> +  ## Additional volumes to the master pod.
```suggestion
  volumeMounts: []
  ## volumeMounts to the master container
  #  - name: locust-file
  #   mountPath: /locust
  volumes: []
  ## volumes for the master pod.
```

2020-12-27 15:58 UTC, hansehe approved these changes

2020-12-27 15:58 UTC, hansehe commented
Thanks! I'll merge it and push a new chart version

2020-12-27 15:59 UTC, merged